import type { ComponentTemplate } from '@/types';

export const COMPONENT_TEMPLATES: ComponentTemplate[] = [
  // Traffic & Edge
  {
    type: 'client',
    label: 'Users',
    category: 'Traffic & Edge',
    description: 'End-user clients (browsers, mobile apps)',
    icon: 'Users',
    color: '#6366f1',
    defaultConfig: { maxRps: 5000, replicas: 1 },
    costPerHour: 0,
  },
  {
    type: 'dns',
    label: 'DNS',
    category: 'Traffic & Edge',
    description: 'Domain Name System resolver',
    icon: 'Globe',
    color: '#8b5cf6',
    defaultConfig: { maxRps: 100000, replicas: 1 },
    costPerHour: 0.01,
  },
  {
    type: 'cdn',
    label: 'CDN',
    category: 'Traffic & Edge',
    description: 'Content Delivery Network (Cloudflare, CloudFront)',
    icon: 'Globe2',
    color: '#3b82f6',
    defaultConfig: { maxRps: 50000, replicas: 1, cacheHitRate: 90 },
    costPerHour: 0.08,
  },
  {
    type: 'waf',
    label: 'WAF',
    category: 'Security',
    description: 'Web Application Firewall',
    icon: 'Shield',
    color: '#ef4444',
    defaultConfig: { maxRps: 30000, replicas: 1 },
    costPerHour: 0.05,
  },
  {
    type: 'loadbalancer',
    label: 'Load Balancer',
    category: 'Traffic & Edge',
    description: 'Distributes traffic across multiple servers',
    icon: 'Shuffle',
    color: '#f59e0b',
    defaultConfig: { maxRps: 10000, replicas: 2, algorithm: 'round-robin' },
    costPerHour: 0.02,
  },
  // Compute
  {
    type: 'apigateway',
    label: 'API Gateway',
    category: 'Compute',
    description: 'API Gateway - routing, auth, rate limiting',
    icon: 'Layers',
    color: '#10b981',
    defaultConfig: { maxRps: 5000, replicas: 2, authEnabled: true },
    costPerHour: 0.04,
  },
  {
    type: 'appserver',
    label: 'App Server',
    category: 'Compute',
    description: 'Application server (Node.js, Python, Java)',
    icon: 'Server',
    color: '#06b6d4',
    defaultConfig: { maxRps: 500, replicas: 3 },
    costPerHour: 0.10,
  },
  {
    type: 'microservice',
    label: 'Microservice',
    category: 'Compute',
    description: 'Independent microservice container',
    icon: 'Box',
    color: '#14b8a6',
    defaultConfig: { maxRps: 1000, replicas: 2 },
    costPerHour: 0.08,
  },
  {
    type: 'worker',
    label: 'Worker',
    category: 'Compute',
    description: 'Background job processor / consumer',
    icon: 'Cpu',
    color: '#84cc16',
    defaultConfig: { maxRps: 200, replicas: 2 },
    costPerHour: 0.07,
  },
  {
    type: 'auth',
    label: 'Auth Service',
    category: 'Security',
    description: 'Authentication & Authorization (OAuth2/JWT)',
    icon: 'KeyRound',
    color: '#f43f5e',
    defaultConfig: { maxRps: 2000, replicas: 2, sslEnabled: true },
    costPerHour: 0.03,
  },
  // Storage
  {
    type: 'database',
    label: 'Database',
    category: 'Storage',
    description: 'Relational/NoSQL database (PostgreSQL, MongoDB)',
    icon: 'Database',
    color: '#a855f7',
    defaultConfig: { maxRps: 3000, replicas: 1, dbType: 'postgres' },
    costPerHour: 0.15,
  },
  {
    type: 'cache',
    label: 'Cache',
    category: 'Storage',
    description: 'In-memory cache (Redis, Memcached)',
    icon: 'Zap',
    color: '#f97316',
    defaultConfig: { maxRps: 50000, replicas: 1, cacheHitRate: 85 },
    costPerHour: 0.06,
  },
  {
    type: 'storage',
    label: 'Object Storage',
    category: 'Storage',
    description: 'Object/blob storage (S3, GCS, Azure Blob)',
    icon: 'HardDrive',
    color: '#64748b',
    defaultConfig: { maxRps: 5000, replicas: 1, storageType: 's3' },
    costPerHour: 0.02,
  },
  {
    type: 'search',
    label: 'Search Engine',
    category: 'Storage',
    description: 'Full-text search (Elasticsearch, Algolia)',
    icon: 'Search',
    color: '#e879f9',
    defaultConfig: { maxRps: 2000, replicas: 3 },
    costPerHour: 0.12,
  },
  // Messaging
  {
    type: 'queue',
    label: 'Message Queue',
    category: 'Messaging',
    description: 'Message broker (Kafka, RabbitMQ, SQS)',
    icon: 'Layers3',
    color: '#eab308',
    defaultConfig: { maxRps: 100000, replicas: 3, queueType: 'kafka' },
    costPerHour: 0.04,
  },
  // Observability
  {
    type: 'monitor',
    label: 'Monitoring',
    category: 'Observability',
    description: 'Metrics & alerts (Prometheus, Grafana, Datadog)',
    icon: 'Activity',
    color: '#34d399',
    defaultConfig: { maxRps: 10000, replicas: 1 },
    costPerHour: 0.05,
  },
  // Advanced
  {
    type: 'servicemesh',
    label: 'Service Mesh',
    category: 'Compute',
    description: 'Service-to-service comms (Istio, Linkerd)',
    icon: 'Network',
    color: '#22d3ee',
    defaultConfig: { maxRps: 20000, replicas: 3 },
    costPerHour: 0.03,
  },
  {
    type: 'circuitbreaker',
    label: 'Circuit Breaker',
    category: 'Compute',
    description: 'Fault tolerance pattern (Hystrix/Resilience4j)',
    icon: 'CircleDashed',
    color: '#fb923c',
    defaultConfig: { maxRps: 5000, replicas: 1 },
    costPerHour: 0.01,
  },
  // Services
  {
    type: 'email',
    label: 'Email Service',
    category: 'Services',
    description: 'Email delivery (SendGrid, SES)',
    icon: 'Mail',
    color: '#94a3b8',
    defaultConfig: { maxRps: 100, replicas: 1 },
    costPerHour: 0.02,
  },
  {
    type: 'payment',
    label: 'Payment Gateway',
    category: 'Services',
    description: 'Payment processing (Stripe, PayPal)',
    icon: 'CreditCard',
    color: '#4ade80',
    defaultConfig: { maxRps: 200, replicas: 2 },
    costPerHour: 0.05,
  },
];

export const CATEGORIES = Array.from(new Set(COMPONENT_TEMPLATES.map(t => t.category)));
